[package]
name        = "darwinia-precompile-assets"
description = "Assets precompile for EVM pallet."
authors     = { workspace = true }
edition     = { workspace = true }
version     = { workspace = true }


[dependencies]
# frontier
fp-evm     = { workspace = true }
pallet-evm = { workspace = true }

# moonbeam
precompile-utils = { workspace = true}

# paritytech
frame-support = { workspace = true }
frame-system  = { workspace = true }
pallet-assets = { workspace = true }
sp-core       = { workspace = true }
sp-std        = { workspace = true }

[dev-dependencies]
# crates.io
codec      = { package = "parity-scale-codec", workspace = true }
scale-info = { workspace = true }
sha3       = { workspace = true }

# moonbeam
precompile-utils = { workspace = true, features = ["testing"] }

# paritytech
pallet-balances  = { workspace = true, features = ["std"] }
pallet-timestamp = { workspace = true, features = ["std"] }
sp-core          = { workspace = true }
sp-io            = { workspace = true }
sp-runtime       = { workspace = true }

[features]
default = ["std"]
std = [
	# frontier
	"fp-evm/std",
	"pallet-evm/std",

	# moonbeam
	"precompile-utils/std",

	# paritytech
	"frame-support/std",
	"frame-system/std",
	"pallet-assets/std",
	"sp-std/std",
	"sp-core/std",
]
