[package]
authors.workspace = true
description       = "Darwinia deposit mechanism implementation."
edition.workspace = true
name              = "darwinia-deposit"
readme            = "README.md"
version.workspace = true

[dependencies]
# crates.io
codec      = { package = "parity-scale-codec", workspace = true }
scale-info = { workspace = true }

# darwinia
darwinia-staking = { workspace = true }
dc-inflation     = { workspace = true }
dc-types         = { workspace = true }

# subtrate
frame-benchmarking = { workspace = true, optional = true }
frame-support      = { workspace = true }
frame-system       = { workspace = true }
pallet-timestamp   = { workspace = true }
sp-core            = { workspace = true }
sp-runtime         = { workspace = true }
sp-std             = { workspace = true }

[dev-dependencies]
# substrate
pallet-assets   = { workspace = true, features = ["std"] }
pallet-balances = { workspace = true, features = ["std"] }
sp-io           = { workspace = true, features = ["std"] }

[features]
default = ["std"]
std = [
	# crates.io
	"codec/std",
	"scale-info/std",

	# darwinia
	"darwinia-staking/std",
	"dc-inflation/std",

	# subtrate
	"frame-support/std",
	"frame-system/std",
	"pallet-timestamp/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
	# substrate optional
	"frame-benchmarking?/std",
]

runtime-benchmarks = [
	# substrate
	"frame-benchmarking/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
]

try-runtime = [
	# substrate
	"frame-support/try-runtime",
]
