[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia parachain staking."
edition     = "2021"
homepage    = "https://darwinia.network"
license     = "GPL-3.0"
name        = "darwinia-staking"
readme      = "README.md"
repository  = "https://github.com/darwinia-network/darwinia"
version     = "6.0.0"

[dependencies]
# crates.io
codec      = { package = "parity-scale-codec", version = "3.3", default-features = false, features = ["derive"] }
scale-info = { version = "2.3", default-features = false }

# darwinia
dc-inflation = { default-features = false, path = "../../core/inflation" }
dc-types     = { path = "../../core/types" }

# subtrate
frame-support     = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37" }
frame-system      = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37" }
pallet-authorship = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37" }
pallet-session    = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37" }
sp-core           = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37" }
sp-runtime        = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37" }
sp-std            = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37" }

[dev-dependencies]
# crates.io
pretty_env_logger = { version = "0.4" }

# darwinia
darwinia-deposit = { path = "../deposit" }

# substrate
pallet-assets    = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37" }
pallet-balances  = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37" }
pallet-session   = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37" }
sp-io            = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37" }

[features]
default = ["std"]
std = [
	# crates.io
	"codec/std",
	"scale-info/std",

	# darwinia
	"dc-inflation/std",

	# subtrate
	"frame-support/std",
	"frame-system/std",
	"pallet-authorship/std",
	"pallet-balances/std",
	"pallet-session/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
]

# TODO: runtime-benchmarks
try-runtime = ["frame-support/try-runtime"]
