[package]
name        = "darwinia-staking"
description = "Darwinia parachain staking."
readme      = "README.md"
authors     = { workspace = true }
edition     = { workspace = true }
version     = { workspace = true }

[dependencies]
# crates.io
codec      = { package = "parity-scale-codec", workspace = true }
scale-info = { workspace = true }

# darwinia
dc-inflation = { workspace = true }
dc-types     = { workspace = true }

# subtrate
frame-support     = { workspace = true }
frame-system      = { workspace = true }
pallet-authorship = { workspace = true }
pallet-session    = { workspace = true }
sp-core           = { workspace = true }
sp-runtime        = { workspace = true }
sp-std            = { workspace = true }

[dev-dependencies]
# crates.io
pretty_env_logger = { version = "0.4" }

# darwinia
darwinia-deposit = { workspace = true }

# substrate
pallet-assets    = { workspace = true, features = ["std"] }
pallet-balances  = { workspace = true, features = ["std"] }
pallet-session   = { workspace = true, features = ["std"] }
pallet-timestamp = { workspace = true, features = ["std"] }
sp-io            = { workspace = true }

[features]
default = ["std"]
std = [
	# crates.io
	"codec/std",
	"scale-info/std",

	# darwinia
	"dc-inflation/std",

	# subtrate
	"frame-support/std",
	"frame-system/std",
	"pallet-authorship/std",
	"pallet-balances/std",
	"pallet-session/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
]

# TODO: runtime-benchmarks
try-runtime = ["frame-support/try-runtime"]
