[package]
name        = "darwinia-precompile-staking"
description = "Staking precompile for EVM pallet."
authors     = { workspace = true }
edition     = { workspace = true }
version     = { workspace = true }

[dependencies]
# frontier
fp-evm     = { workspace = true }
pallet-evm = { workspace = true }

# darwinia
darwinia-staking = { workspace = true }

# moonbeam
precompile-utils = { workspace = true }

# substrate
frame-support = { workspace = true }
frame-system  = { workspace = true }
sp-core       = { workspace = true }
sp-runtime    = { workspace = true }
sp-std        = { workspace = true }

[dev-dependencies]
# crates.io
codec      = { workspace = true, package = "parity-scale-codec" }
scale-info = { workspace = true }

# darwinia
darwinia-deposit = { workspace = true }

# moonbeam
precompile-utils = { workspace = true, features = ["testing"] }

# substrate
frame-system     = { workspace = true }
pallet-balances  = { workspace = true, features = ["std"] }
pallet-timestamp = { workspace = true, features = ["std"] }
sp-io            = { workspace = true }

[features]
default = ["std"]
std = [
	# frontier
	"fp-evm/std",
	"pallet-evm/std",

	# darwinia
	"darwinia-staking/std",

	# moonbeam
	"precompile-utils/std",

	# substrate
	"frame-support/std",
	"frame-system/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
]
