[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia Common Runtime"
edition     = "2021"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "darwinia-common-runtime"
readme      = "README.md"
repository  = "https://github.com/darwinia-network/darwinia"
version     = "6.0.0"

[dependencies]
# darwinia
dc-primitives = { default-features = false, path = "../../core/primitives" }

# darwinia-messages-substrate
bp-darwinia-core = { default-features = false, git = "https://github.com/darwinia-network/darwinia-messages-substrate", branch = "guantong/support-H160" }

# polkadot
xcm          = { default-features = false, git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.30" }
xcm-executor = { default-features = false, git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.30" }

# substrate
frame-support     = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.30" }
frame-system      = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.30" }
pallet-collective = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.30" }

[features]
default = ["std"]
std = [
	# darwinia
	"dc-primitives/std",

	# polkadot
	"xcm/std",
	"xcm-executor/std",

	# substrate
	"frame-support/std",
	"frame-system/std",
	"pallet-collective/std",
]
