[package]
name        = "darwinia-common-runtime"
description = "Darwinia Common Runtime"
authors     = { workspace = true }
edition     = { workspace = true }
version     = { workspace = true }


[dependencies]
# crates.io
codec    = { package = "parity-scale-codec", workspace = true }
smallvec = { version = "1.10" }

# darwinia
dc-primitives = { workspace = true }

# darwinia-messages-substrate
bp-darwinia-core = { workspace = true }

# moonbeam
account = { workspace = true }

# polkadot
xcm          = { workspace = true }
xcm-builder  = { workspace = true }
xcm-executor = { workspace = true }

# substrate
frame-support     = { workspace = true }
frame-system      = { workspace = true }
pallet-collective = { workspace = true }
sp-io             = { workspace = true }
sp-runtime        = { workspace = true }
sp-std            = { workspace = true }

[features]
default = ["std"]
std = [
	# crates.io
	"codec/std",

	# darwinia
	"dc-primitives/std",

	# darwinia-messages-substrate
	"bp-darwinia-core/std",

	# moonbeam
	"account/std",

	# polkadot
	"xcm/std",
	"xcm-builder/std",
	"xcm-executor/std",

	# substrate
	"frame-support/std",
	"frame-system/std",
	"pallet-collective/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]

test = []
