[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "State storage precompiles for EVM pallet."
edition     = "2021"
homepage    = "https://darwinia.network"
license     = "GPL-3.0"
name        = "darwinia-precompile-bls12-381"
readme      = "README.md"
repository  = "https://github.com/darwinia-network/darwinia"
version     = "6.0.0"

[dependencies]
# crates.io
milagro_bls = { default-features = false, git = "https://github.com/darwinia-network/milagro_bls" }

# frontier
fp-evm     = { default-features = false, git = "https://github.com/darwinia-network/frontier", branch = "prepare-polkadot-v0.9.33" }
pallet-evm = { default-features = false, git = "https://github.com/darwinia-network/frontier", branch = "prepare-polkadot-v0.9.33" }

# moonbeam
precompile-utils = { default-features = false, git = "https://github.com/darwinia-network/moonbeam", branch = "prepare-polkadot-v0.9.33" }

# substrate
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }
sp-std        = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }

[dev-dependencies]
# crates.io
codec      = { package = "parity-scale-codec", version = "3.2" }
scale-info = { version = "2.3", features = ["derive"] }

# moonbeam
precompile-utils = { git = "https://github.com/darwinia-network/moonbeam", branch = "prepare-polkadot-v0.9.33", features = ["testing"] }

# substrate
frame-system     = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }
pallet-balances  = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }
sp-core          = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }
sp-io            = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }
sp-runtime       = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }

[features]
default = ["std"]
std = [
	# frontier
	"fp-evm/std",
	"pallet-evm/std",

	# moonbeam
	"precompile-utils/std",

	# substrate
	"frame-support/std",
	"sp-std/std",
]
