[package]
name        = "dc-types"
description = "Darwinia core types."
readme      = "README.md"
authors     = { workspace = true }
edition     = { workspace = true }
version     = { workspace = true }
