[package]
name        = "darwinia-precompile-deposit"
description = "Deposit precompile for EVM pallet."
authors     = { workspace = true }
edition     = { workspace = true }
version     = { workspace = true }


[dependencies]
# frontier
fp-evm     = { workspace = true }
pallet-evm = { workspace = true }

# darwinia
darwinia-deposit = { workspace = true }

# moonbeam
precompile-utils = { workspace = true }

# substrate
frame-support = { workspace = true }
frame-system  = { workspace = true }
sp-core       = { workspace = true }
sp-std        = { workspace = true }

[dev-dependencies]
# crates.io
codec      = { package = "parity-scale-codec", workspace = true }
scale-info = { workspace = true }

# moonbeam
precompile-utils = { workspace = true, features = ["testing"] }

# substrate
pallet-balances  = { workspace = true, features = ["std"] }
pallet-timestamp = { workspace = true, features = ["std"] }
sp-io            = { workspace = true }
sp-runtime       = { workspace = true }

[features]
default = ["std"]
std = [
	# frontier
	"fp-evm/std",
	"pallet-evm/std",

	# darwinia
	"darwinia-deposit/std",

	# moonbeam
	"precompile-utils/std",

	# substrate
	"frame-support/std",
	"frame-system/std",
	"sp-core/std",
	"sp-std/std",
]
