[package]
authors.workspace = true
description       = "Darwinia node."
edition.workspace = true
name              = "darwinia"
readme            = "README.md"
version.workspace = true

[build-dependencies]
substrate-build-script-utils = { workspace = true }

[dependencies]
# crates.io
array-bytes = { workspace = true }
async-trait = { version = "0.1" }
clap        = { version = "4.0", features = ["derive"] }
codec       = { package = "parity-scale-codec", workspace = true }
futures     = { version = "0.3" }
jsonrpsee   = { version = "0.16", features = ["server"] }
log         = { version = "0.4" }
serde       = { version = "1.0", features = ["derive"] }

# cumulus
cumulus-client-cli                    = { workspace = true }
cumulus-client-collator               = { workspace = true }
cumulus-client-consensus-aura         = { workspace = true }
cumulus-client-consensus-common       = { workspace = true }
cumulus-client-network                = { workspace = true }
cumulus-client-service                = { workspace = true }
cumulus-primitives-core               = { workspace = true, features = ["std"] }
cumulus-primitives-parachain-inherent = { workspace = true }
cumulus-relay-chain-interface         = { workspace = true }

# darwinia
crab-runtime     = { optional = true, workspace = true }
darwinia-runtime = { optional = true, workspace = true }
dc-primitives    = { workspace = true }
pangolin-runtime = { optional = true, workspace = true }
pangoro-runtime  = { optional = true, workspace = true }

# frontier
fc-cli          = { workspace = true }
fc-consensus    = { workspace = true }
fc-db           = { workspace = true }
fc-mapping-sync = { workspace = true }
fc-rpc          = { features = ["rpc_binary_search_estimate"], workspace = true }
fc-rpc-core     = { workspace = true }
fp-evm          = { workspace = true }
fp-rpc          = { workspace = true }
fp-storage      = { workspace = true }

# polkadot
polkadot-cli        = { workspace = true }
polkadot-parachain  = { workspace = true }
polkadot-primitives = { workspace = true }
polkadot-service    = { workspace = true }
xcm                 = { workspace = true }

# substrate
frame-benchmarking             = { workspace = true }
frame-benchmarking-cli         = { workspace = true }
pallet-transaction-payment-rpc = { workspace = true }
sc-basic-authorship            = { workspace = true }
sc-chain-spec                  = { workspace = true }
sc-cli                         = { workspace = true }
sc-client-api                  = { workspace = true }
sc-consensus                   = { workspace = true }
sc-consensus-aura              = { workspace = true }
sc-executor                    = { workspace = true }
sc-keystore                    = { workspace = true }
sc-network                     = { workspace = true }
sc-network-common              = { workspace = true }
sc-offchain                    = { workspace = true }
sc-rpc                         = { workspace = true }
sc-rpc-api                     = { workspace = true }
sc-service                     = { workspace = true }
sc-sysinfo                     = { workspace = true }
sc-telemetry                   = { workspace = true }
sc-tracing                     = { workspace = true }
sc-transaction-pool            = { workspace = true }
sc-transaction-pool-api        = { workspace = true }
sp-api                         = { workspace = true }
sp-block-builder               = { workspace = true }
sp-blockchain                  = { workspace = true }
sp-consensus                   = { workspace = true }
sp-consensus-aura              = { workspace = true }
sp-core                        = { workspace = true }
sp-inherents                   = { workspace = true }
sp-io                          = { workspace = true }
sp-keystore                    = { workspace = true }
sp-offchain                    = { workspace = true }
sp-runtime                     = { workspace = true }
sp-session                     = { workspace = true }
sp-timestamp                   = { workspace = true }
sp-transaction-pool            = { workspace = true }
substrate-frame-rpc-system     = { workspace = true }
substrate-prometheus-endpoint  = { workspace = true }
try-runtime-cli                = { optional = true, workspace = true }

[features]
default = [
	"crab-native",
	"darwinia-native",
]

fast-runtime = [
	# darwinia
	"crab-runtime?/fast-runtime",
	"darwinia-runtime?/fast-runtime",
	"pangolin-runtime?/fast-runtime",
	"pangoro-runtime?/fast-runtime",
]

runtime-benchmarks = [
	# darwinia
	"crab-runtime?/runtime-benchmarks",
	"darwinia-runtime?/runtime-benchmarks",
	"pangolin-runtime?/runtime-benchmarks",
	"pangoro-runtime?/runtime-benchmarks",

	# polkadot
	"polkadot-cli/runtime-benchmarks",
]

try-runtime = [
	# darwinia
	"crab-runtime?/try-runtime",
	"darwinia-runtime?/try-runtime",
	"pangolin-runtime?/try-runtime",
	"pangoro-runtime?/try-runtime",

	# substrate
	"try-runtime-cli/try-runtime",
]

all-natives = [
	# darwinia
	"crab-native",
	"darwinia-native",
	"pangolin-native",
	"pangoro-native",
]
crab-native = [
	# darwinia
	"crab-runtime",

	# polkadot
	"polkadot-cli/kusama-native",
]
darwinia-native = [
	# darwinia
	"darwinia-runtime",

	# polkadot
	"polkadot-cli/polkadot-native",
]
pangolin-native = [
	# darwinia
	"pangolin-runtime",

	# polkadot
	"polkadot-cli/rococo-native",
]
pangoro-native = [
	# darwinia
	"pangoro-runtime",

	# polkadot
	"polkadot-cli/rococo-native",
]
