[package]
name        = "darwinia-message-transact"
description = "LCMP evm message execution."
readme      = "README.md"
authors     = { workspace = true }
edition     = { workspace = true }
version     = { workspace = true }

[dependencies]
# crates.io
codec      = { package = "parity-scale-codec", workspace = true }
ethereum   = { version = "0.14", default-features = false, features = ["with-codec"] }
scale-info = { workspace = true }

# frontier
fp-ethereum = { workspace = true }
fp-evm      = { workspace = true }
pallet-evm  = { workspace = true }

# substrate
frame-support = { workspace = true }
frame-system  = { workspace = true }
sp-core       = { workspace = true }
sp-runtime    = { workspace = true }
sp-std        = { workspace = true }

[dev-dependencies]
array-bytes  = { workspace = true }
libsecp256k1 = { workspace = true }
rlp          = { version = "0.5" }
sha3         = { workspace = true }

# darwinia
bp-message-dispatch    = { workspace = true, features = ["std"] }
bp-runtime             = { workspace = true }
pallet-bridge-dispatch = { workspace = true }

# frontier
fp-self-contained = { workspace = true }
pallet-ethereum   = { workspace = true }

# moonbeam
precompile-utils = { workspace = true, features = ["testing"] }

# substrate
pallet-balances  = { workspace = true, features = ["std"] }
pallet-timestamp = { workspace = true, features = ["std"] }
sp-io            = { workspace = true }

[features]
default = ["std"]
std = [
	# crates.io
	"codec/std",
	"ethereum/std",
	"scale-info/std",

	# frontier
	"fp-evm/std",
	"fp-ethereum/std",
	"pallet-evm/std",

	# substrate
	"frame-support/std",
	"frame-system/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
]

try-runtime = ["frame-support/try-runtime"]
