[package]
authors = ["Xavier Lau <xavier@inv.cafe>"]
edition = "2021"
name    = "state-processor"
version = "0.0.0"

[dependencies]
# crates.io
anyhow             = { version = "1.0" }
array-bytes        = { version = "6.0" }
fxhash             = { version = "0.2" }
log                = { version = "0.4" }
once_cell          = { version = "1.16" }
parity-scale-codec = { version = "3.2", features = ["derive"] }
pretty_env_logger  = { version = "0.4" }
primitive-types    = { version = "0.12.1", features = ["codec"] }
serde              = { version = "1.0" }
serde_json         = { version = "1.0" }
tar                = { version = "0.4" }
ureq               = { version = "2.6" }
zstd               = { version = "0.12" }

# hack-ink
subhasher   = { git = "https://github.com/hack-ink/subalfred" }
subspector  = { git = "https://github.com/hack-ink/subalfred" }
substorager = { git = "https://github.com/hack-ink/subalfred" }

[workspace]
exclude = []
